In [2]:
import pandas as pd
import numpy as np

In [3]:
print("hello")

hello

In [4]:
df = pd.read_csv("C:/Users/jio86/OneDrive/Desktop/cloud-cost-forecast/datasets/container_scheduling_dataset_10000.csv")

df.head()

,Container_ID,Tenant_ID,Requested_CPU_Cores,Requested_Memory_MB,Requested_Storage_GB,Requested_Bandwidth_Mbps,Execution_Start_Time_ms,Execution_Finish_Time_ms,Makespan_ms,Server_ID,...,Routing_Path_Efficiency,Bandwidth_Allocation_Mbps,Active_Switches,Energy_Efficiency_Score,Execution_Cost_$,Resource_Utilization_%,SLA_Violation_Rate_%,Power_Consumption_Switches_Watts,Total_Data_Transferred_MB,Optimal_Scheduling
0,1,39,1,16146,468,3022,3075776,7684166,4608390,160,...,0.34,567,13,0.67,290.25,37.23,8.89,125.81,20032,0
1,2,29,4,7243,336,2928,1261993,6821675,5559682,177,...,0.86,292,17,0.19,136.11,40.93,4.73,331.63,3735,0
2,3,15,3,28467,636,1170,3818859,7544249,3725390,90,...,0.97,1731,1,0.05,389.96,95.60,14.31,214.86,13211,1
3,4,43,2,11477,186,3991,1442850,7721443,6278593,185,...,0.51,1308,11,0.49,299.44,32.56,47.52,96.43,39594,0
4,5,8,9,28078,546,3620,4735418,6391219,1655801,65,...,0.32,1915,15,1.00,349.23,38.33,2.55,222.94,38243,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Container_ID                              10000 non-null  int64
 1   Tenant_ID                                 10000 non-null  int64
 2   Requested_CPU_Cores                       10000 non-null  int64
 3   Requested_Memory_MB                       10000 non-null  int64
 4   Requested_Storage_GB                      10000 non-null  int64
 5   Requested_Bandwidth_Mbps                  10000 non-null  int64
 6   Execution_Start_Time_ms                   10000 non-null  int64
 7   Execution_Finish_Time_ms                  10000 non-null  int64
 8   Makespan_ms                               10000 non-null  int64
 9   Server_ID                                 10000 non-null  int64
 10  Available_CPU_Cores                       10000 non-null  int64
 11  Available_Memory_GB                       10000 non-null  int64
 12  Available_Storage_TB                      10000 non-null  float64
 13  Available_Bandwidth_Mbps                  10000 non-null  int64
 14  Power_Consumption_Watts                   10000 non-null  float64
 15  Inter_Container_Communication_Latency_ms  10000 non-null  int64
 16  Routing_Path_Efficiency                   10000 non-null  float64
 17  Bandwidth_Allocation_Mbps                 10000 non-null  int64
 18  Active_Switches                           10000 non-null  int64
 19  Energy_Efficiency_Score                   10000 non-null  float64
 20  Execution_Cost_$                          10000 non-null  float64
 21  Resource_Utilization_%                    10000 non-null  float64
 22  SLA_Violation_Rate_%                      10000 non-null  float64
 23  Power_Consumption_Switches_Watts          10000 non-null  float64
 24  Total_Data_Transferred_MB                 10000 non-null  int64
 25  Optimal_Scheduling                        10000 non-null  int64
dtypes: float64(8), int64(18)
memory usage: 2.0 MB

In [6]:
df.describe()

,Container_ID,Tenant_ID,Requested_CPU_Cores,Requested_Memory_MB,Requested_Storage_GB,Requested_Bandwidth_Mbps,Execution_Start_Time_ms,Execution_Finish_Time_ms,Makespan_ms,Server_ID,...,Routing_Path_Efficiency,Bandwidth_Allocation_Mbps,Active_Switches,Energy_Efficiency_Score,Execution_Cost_$,Resource_Utilization_%,SLA_Violation_Rate_%,Power_Consumption_Switches_Watts,Total_Data_Transferred_MB,Optimal_Scheduling
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,25.151500,8.034400,16722.148100,502.933700,2528.68710,2.546831e+06,7.503782e+06,4.956951e+06,99.963200,...,0.502376,2519.928800,10.009800,0.497449,248.285747,55.145845,25.203530,259.088434,25069.866900,0.081500
std,2886.89568,14.083223,4.336646,9205.205877,288.946157,1438.05883,1.405136e+06,1.432174e+06,2.002687e+06,57.512084,...,0.288930,1443.953011,5.504974,0.288715,143.720516,26.040711,14.458321,141.834241,14554.864272,0.273615
min,1.00000,1.000000,1.000000,515.000000,1.000000,10.00000,1.017590e+05,5.001282e+06,2.005200e+04,1.000000,...,0.000000,10.000000,1.000000,0.000000,0.500000,10.010000,0.000000,10.010000,103.000000,0.000000
25%,2500.75000,13.000000,4.000000,8955.750000,258.000000,1294.00000,1.348248e+06,6.289992e+06,3.532296e+06,50.000000,...,0.250000,1266.000000,5.000000,0.250000,123.552500,32.820000,12.490000,137.047500,12402.000000,0.000000
50%,5000.50000,25.000000,8.000000,16741.500000,502.000000,2545.00000,2.531804e+06,7.498304e+06,4.951374e+06,100.000000,...,0.510000,2533.500000,10.000000,0.490000,246.700000,54.875000,25.335000,262.635000,24922.000000,0.000000
75%,7500.25000,37.000000,12.000000,24661.500000,754.000000,3761.25000,3.765810e+06,8.736502e+06,6.375442e+06,150.000000,...,0.750000,3782.250000,15.000000,0.740000,372.682500,77.852500,37.662500,382.920000,37746.250000,0.000000
max,10000.00000,49.000000,15.000000,32764.000000,999.000000,4999.00000,4.999884e+06,9.999846e+06,9.838945e+06,199.000000,...,1.000000,4999.000000,19.000000,1.000000,499.940000,99.980000,50.000000,499.980000,49999.000000,1.000000

In [7]:
df = pd.read_csv("../datasets/container_scheduling_dataset_10000.csv")

In [8]:
df.head()

,Container_ID,Tenant_ID,Requested_CPU_Cores,Requested_Memory_MB,Requested_Storage_GB,Requested_Bandwidth_Mbps,Execution_Start_Time_ms,Execution_Finish_Time_ms,Makespan_ms,Server_ID,...,Routing_Path_Efficiency,Bandwidth_Allocation_Mbps,Active_Switches,Energy_Efficiency_Score,Execution_Cost_$,Resource_Utilization_%,SLA_Violation_Rate_%,Power_Consumption_Switches_Watts,Total_Data_Transferred_MB,Optimal_Scheduling
0,1,39,1,16146,468,3022,3075776,7684166,4608390,160,...,0.34,567,13,0.67,290.25,37.23,8.89,125.81,20032,0
1,2,29,4,7243,336,2928,1261993,6821675,5559682,177,...,0.86,292,17,0.19,136.11,40.93,4.73,331.63,3735,0
2,3,15,3,28467,636,1170,3818859,7544249,3725390,90,...,0.97,1731,1,0.05,389.96,95.60,14.31,214.86,13211,1
3,4,43,2,11477,186,3991,1442850,7721443,6278593,185,...,0.51,1308,11,0.49,299.44,32.56,47.52,96.43,39594,0
4,5,8,9,28078,546,3620,4735418,6391219,1655801,65,...,0.32,1915,15,1.00,349.23,38.33,2.55,222.94,38243,0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Container_ID                              10000 non-null  int64
 1   Tenant_ID                                 10000 non-null  int64
 2   Requested_CPU_Cores                       10000 non-null  int64
 3   Requested_Memory_MB                       10000 non-null  int64
 4   Requested_Storage_GB                      10000 non-null  int64
 5   Requested_Bandwidth_Mbps                  10000 non-null  int64
 6   Execution_Start_Time_ms                   10000 non-null  int64
 7   Execution_Finish_Time_ms                  10000 non-null  int64
 8   Makespan_ms                               10000 non-null  int64
 9   Server_ID                                 10000 non-null  int64
 10  Available_CPU_Cores                       10000 non-null  int64
 11  Available_Memory_GB                       10000 non-null  int64
 12  Available_Storage_TB                      10000 non-null  float64
 13  Available_Bandwidth_Mbps                  10000 non-null  int64
 14  Power_Consumption_Watts                   10000 non-null  float64
 15  Inter_Container_Communication_Latency_ms  10000 non-null  int64
 16  Routing_Path_Efficiency                   10000 non-null  float64
 17  Bandwidth_Allocation_Mbps                 10000 non-null  int64
 18  Active_Switches                           10000 non-null  int64
 19  Energy_Efficiency_Score                   10000 non-null  float64
 20  Execution_Cost_$                          10000 non-null  float64
 21  Resource_Utilization_%                    10000 non-null  float64
 22  SLA_Violation_Rate_%                      10000 non-null  float64
 23  Power_Consumption_Switches_Watts          10000 non-null  float64
 24  Total_Data_Transferred_MB                 10000 non-null  int64
 25  Optimal_Scheduling                        10000 non-null  int64
dtypes: float64(8), int64(18)
memory usage: 2.0 MB

In [10]:
df.describe()

,Container_ID,Tenant_ID,Requested_CPU_Cores,Requested_Memory_MB,Requested_Storage_GB,Requested_Bandwidth_Mbps,Execution_Start_Time_ms,Execution_Finish_Time_ms,Makespan_ms,Server_ID,...,Routing_Path_Efficiency,Bandwidth_Allocation_Mbps,Active_Switches,Energy_Efficiency_Score,Execution_Cost_$,Resource_Utilization_%,SLA_Violation_Rate_%,Power_Consumption_Switches_Watts,Total_Data_Transferred_MB,Optimal_Scheduling
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,25.151500,8.034400,16722.148100,502.933700,2528.68710,2.546831e+06,7.503782e+06,4.956951e+06,99.963200,...,0.502376,2519.928800,10.009800,0.497449,248.285747,55.145845,25.203530,259.088434,25069.866900,0.081500
std,2886.89568,14.083223,4.336646,9205.205877,288.946157,1438.05883,1.405136e+06,1.432174e+06,2.002687e+06,57.512084,...,0.288930,1443.953011,5.504974,0.288715,143.720516,26.040711,14.458321,141.834241,14554.864272,0.273615
min,1.00000,1.000000,1.000000,515.000000,1.000000,10.00000,1.017590e+05,5.001282e+06,2.005200e+04,1.000000,...,0.000000,10.000000,1.000000,0.000000,0.500000,10.010000,0.000000,10.010000,103.000000,0.000000
25%,2500.75000,13.000000,4.000000,8955.750000,258.000000,1294.00000,1.348248e+06,6.289992e+06,3.532296e+06,50.000000,...,0.250000,1266.000000,5.000000,0.250000,123.552500,32.820000,12.490000,137.047500,12402.000000,0.000000
50%,5000.50000,25.000000,8.000000,16741.500000,502.000000,2545.00000,2.531804e+06,7.498304e+06,4.951374e+06,100.000000,...,0.510000,2533.500000,10.000000,0.490000,246.700000,54.875000,25.335000,262.635000,24922.000000,0.000000
75%,7500.25000,37.000000,12.000000,24661.500000,754.000000,3761.25000,3.765810e+06,8.736502e+06,6.375442e+06,150.000000,...,0.750000,3782.250000,15.000000,0.740000,372.682500,77.852500,37.662500,382.920000,37746.250000,0.000000
max,10000.00000,49.000000,15.000000,32764.000000,999.000000,4999.00000,4.999884e+06,9.999846e+06,9.838945e+06,199.000000,...,1.000000,4999.000000,19.000000,1.000000,499.940000,99.980000,50.000000,499.980000,49999.000000,1.000000

In [11]:
df.columns

Index(['Container_ID', 'Tenant_ID', 'Requested_CPU_Cores',
       'Requested_Memory_MB', 'Requested_Storage_GB',
       'Requested_Bandwidth_Mbps', 'Execution_Start_Time_ms',
       'Execution_Finish_Time_ms', 'Makespan_ms', 'Server_ID',
       'Available_CPU_Cores', 'Available_Memory_GB', 'Available_Storage_TB',
       'Available_Bandwidth_Mbps', 'Power_Consumption_Watts',
       'Inter_Container_Communication_Latency_ms', 'Routing_Path_Efficiency',
       'Bandwidth_Allocation_Mbps', 'Active_Switches',
       'Energy_Efficiency_Score', 'Execution_Cost_$', 'Resource_Utilization_%',
       'SLA_Violation_Rate_%', 'Power_Consumption_Switches_Watts',
       'Total_Data_Transferred_MB', 'Optimal_Scheduling'],
      dtype='str')

In [12]:
features = [
    "Requested_CPU_Cores",
    "Requested_Memory_MB",
    "Requested_Storage_GB",
    "Requested_Bandwidth_Mbps",
    "Power_Consumption_Switches_Watts",
    "Resource_Utilization_%",
    "Energy_Efficiency_Score",
    "SLA_Violation_Rate_%",
    "Total_Data_Transferred_MB"
]

X = df[features]

y = df["Execution_Cost_$"]

print(X.head())

print("\nTarget:")
print(y.head())

   Requested_CPU_Cores  Requested_Memory_MB  Requested_Storage_GB  \
0                    1                16146                   468
1                    4                 7243                   336
2                    3                28467                   636
3                    2                11477                   186
4                    9                28078                   546

   Requested_Bandwidth_Mbps  Power_Consumption_Switches_Watts  \
0                      3022                            125.81
1                      2928                            331.63
2                      1170                            214.86
3                      3991                             96.43
4                      3620                            222.94

   Resource_Utilization_%  Energy_Efficiency_Score  SLA_Violation_Rate_%  \
0                   37.23                     0.67                  8.89
1                   40.93                     0.19                  4.73
2                   95.60                     0.05                 14.31
3                   32.56                     0.49                 47.52
4                   38.33                     1.00                  2.55

   Total_Data_Transferred_MB
0                      20032
1                       3735
2                      13211
3                      39594
4                      38243

Target:
0    290.25
1    136.11
2    389.96
3    299.44
4    349.23
Name: Execution_Cost_$, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (8000, 9)
Testing data shape: (2000, 9)

In [14]:
from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Scale training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
from sklearn.svm import SVR

# Create SVR model
model = SVR(kernel='rbf')

# Train model
model.fit(X_train_scaled, y_train)

print("SVR model trained successfully")

SVR model trained successfully

In [16]:
# Predict
y_pred = model.predict(X_test_scaled)

print(y_pred[:5])

[246.39536066 255.23211446 241.46205519 246.84811904 249.11734223]

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 123.41999384727012
RMSE: 142.89011988406438
R2 Score: -0.002721412287302938

In [18]:
correlation = df.corr(numeric_only=True)

correlation["Execution_Cost_$"].sort_values(ascending=False)

Execution_Cost_$                            1.000000
Server_ID                                   0.013877
Inter_Container_Communication_Latency_ms    0.013166
Routing_Path_Efficiency                     0.012944
Requested_Bandwidth_Mbps                    0.010789
Execution_Start_Time_ms                     0.009965
Available_Bandwidth_Mbps                    0.009124
Requested_Memory_MB                         0.009027
Power_Consumption_Watts                     0.008187
Active_Switches                             0.008061
Power_Consumption_Switches_Watts            0.007752
Container_ID                                0.005694
Available_CPU_Cores                         0.003753
SLA_Violation_Rate_%                        0.001523
Available_Memory_GB                         0.000873
Available_Storage_TB                       -0.001132
Total_Data_Transferred_MB                  -0.002867
Energy_Efficiency_Score                    -0.004106
Requested_Storage_GB                       -0.005302
Tenant_ID                                  -0.006948
Resource_Utilization_%                     -0.007554
Bandwidth_Allocation_Mbps                  -0.008508
Optimal_Scheduling                         -0.008823
Execution_Finish_Time_ms                   -0.011344
Requested_CPU_Cores                        -0.011932
Makespan_ms                                -0.015104
Name: Execution_Cost_$, dtype: float64

In [19]:
df["Better_Execution_Cost"] = (
    df["Requested_CPU_Cores"] * 15 +
    df["Requested_Memory_MB"] * 0.02 +
    df["Requested_Bandwidth_Mbps"] * 0.05 +
    df["Power_Consumption_Watts"] * 0.03 +
    df["Total_Data_Transferred_MB"] * 0.01
)

In [20]:
correlation = df.corr(numeric_only=True)

correlation["Better_Execution_Cost"].sort_values(ascending=False)

Better_Execution_Cost                       1.000000
Requested_Memory_MB                         0.731654
Total_Data_Transferred_MB                   0.572780
Requested_Bandwidth_Mbps                    0.280310
Requested_CPU_Cores                         0.268000
Power_Consumption_Watts                     0.030421
Available_Memory_GB                         0.020075
Energy_Efficiency_Score                     0.015577
Bandwidth_Allocation_Mbps                   0.013594
Inter_Container_Communication_Latency_ms    0.013243
Makespan_ms                                 0.010118
Available_CPU_Cores                         0.008295
Available_Storage_TB                        0.006879
Execution_Finish_Time_ms                    0.006628
Routing_Path_Efficiency                     0.006483
Requested_Storage_GB                        0.005897
Execution_Cost_$                            0.005124
Optimal_Scheduling                         -0.003044
Server_ID                                  -0.003870
Power_Consumption_Switches_Watts           -0.005877
Execution_Start_Time_ms                    -0.007665
Tenant_ID                                  -0.007897
Resource_Utilization_%                     -0.008693
Available_Bandwidth_Mbps                   -0.010249
Container_ID                               -0.010724
SLA_Violation_Rate_%                       -0.011212
Active_Switches                            -0.012627
Name: Better_Execution_Cost, dtype: float64

In [21]:
features = [
    "Requested_CPU_Cores",
    "Requested_Memory_MB",
    "Requested_Storage_GB",
    "Requested_Bandwidth_Mbps",
    "Power_Consumption_Watts",
    "Total_Data_Transferred_MB"
]

X = df[features]

y = df["Better_Execution_Cost"]

In [22]:
from sklearn.model_selection import train_test_split

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: (8000, 6)
Testing shape: (2000, 6)

In [23]:
from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Scale training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale testing data
X_test_scaled = scaler.transform(X_test)

print("Scaling completed")

Scaling completed

In [24]:
from sklearn.svm import SVR

# Create SVR model
model = SVR(kernel='rbf')

# Train model
model.fit(X_train_scaled, y_train)

print("SVR trained successfully")

SVR trained successfully

In [25]:
# Predict on test data
y_pred = model.predict(X_test_scaled)

print("First 5 Predictions:")
print(y_pred[:5])

First 5 Predictions:
[1145.5924429   676.33032277  837.1676469   867.03740489 1111.47910987]

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

# Print results
print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 47.225130232141396
RMSE: 76.19769700313924
R2 Score: 0.9109357192552211

In [27]:
import joblib

In [28]:
joblib.dump(model, "../models/svr_cloud_cost_model.pkl")

print("Model saved successfully")

Model saved successfully

In [29]:
import joblib

joblib.dump(scaler, "../models/scaler.pkl")

print("Scaler saved successfully")

Scaler saved successfully